CREATE TABLE IF NOT EXISTS pet (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('GATO', 'CACHORRO')),
    sexo VARCHAR(20) NOT NULL CHECK (sexo IN ('MACHO', 'FEMEA')),
    endereco VARCHAR(255) NOT NULL,
    idade DOUBLE PRECISION NOT NULL CHECK (idade >= 0),
    peso DOUBLE PRECISION NOT NULL CHECK (peso > 0),
    raca VARCHAR(50) NOT NULL
);